# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1790, 1244)
        Form.setStyleSheet("")
        self.sql_tbl = QtWidgets.QTableWidget(Form)
        self.sql_tbl.setGeometry(QtCore.QRect(10, 710, 1761, 521))
        self.sql_tbl.setMinimumSize(QtCore.QSize(1491, 0))
        self.sql_tbl.setColumnCount(17)
        self.sql_tbl.setObjectName("sql_tbl")
        self.sql_tbl.setRowCount(0)
        self.sql_tbl.horizontalHeader().setMinimumSectionSize(32)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(1260, 10, 511, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.cmb_hafta = QtWidgets.QComboBox(self.groupBox_2)
        self.cmb_hafta.setGeometry(QtCore.QRect(260, 60, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cmb_hafta.setFont(font)
        self.cmb_hafta.setObjectName("cmb_hafta")
        self.cmb_hafta.addItem("")
        self.cmb_hafta.addItem("")
        self.cmb_hafta.addItem("")
        self.cmb_hafta.addItem("")
        self.cmb_hafta.addItem("")
        self.cmb_hafta.addItem("")
        self.cmb_hafta.addItem("")
        self.cmb_hafta.addItem("")
        self.cmb_hafta.addItem("")
        self.cmb_hafta.addItem("")
        self.cmb_hafta.addItem("")
        self.cmb_hafta.addItem("")
        self.cmb_hafta.addItem("")
        self.cmb_hafta.addItem("")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.yklm_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.yklm_btn.setGeometry(QtCore.QRect(140, 140, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.yklm_btn.setFont(font)
        self.yklm_btn.setObjectName("yklm_btn")
        self.yoklama_bt = QtWidgets.QPushButton(Form)
        self.yoklama_bt.setGeometry(QtCore.QRect(810, 520, 161, 81))
        self.yoklama_bt.setObjectName("yoklama_bt")
        self.qrcode_bt = QtWidgets.QPushButton(Form)
        self.qrcode_bt.setGeometry(QtCore.QRect(630, 520, 161, 81))
        self.qrcode_bt.setAutoFillBackground(False)
        self.qrcode_bt.setObjectName("qrcode_bt")
        self.cikis_bt = QtWidgets.QPushButton(Form)
        self.cikis_bt.setGeometry(QtCore.QRect(630, 610, 521, 81))
        self.cikis_bt.setObjectName("cikis_bt")
        self.image_label = QtWidgets.QLabel(Form)
        self.image_label.setGeometry(QtCore.QRect(600, 10, 581, 491))
        self.image_label.setFrameShape(QtWidgets.QFrame.Box)
        self.image_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.image_label.setLineWidth(5)
        self.image_label.setMidLineWidth(4)
        self.image_label.setText("")
        self.image_label.setPixmap(QtGui.QPixmap(".\\webcam.png"))
        self.image_label.setScaledContents(False)
        self.image_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.image_label.setWordWrap(False)
        self.image_label.setIndent(-1)
        self.image_label.setObjectName("image_label")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 511, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(11, 50, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(11, 120, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(11, 190, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(260, 60, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(260, 130, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(260, 200, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.control_bt = QtWidgets.QPushButton(Form)
        self.control_bt.setGeometry(QtCore.QRect(990, 520, 161, 81))
        self.control_bt.setObjectName("control_bt")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "QR Kod Yoklama"))
        self.groupBox_2.setTitle(_translate("Form", "Yoklama Başlat"))
        self.cmb_hafta.setItemText(0, _translate("Form", "Hafta1"))
        self.cmb_hafta.setItemText(1, _translate("Form", "Hafta2"))
        self.cmb_hafta.setItemText(2, _translate("Form", "Hafta3"))
        self.cmb_hafta.setItemText(3, _translate("Form", "Hafta4"))
        self.cmb_hafta.setItemText(4, _translate("Form", "Hafta5"))
        self.cmb_hafta.setItemText(5, _translate("Form", "Hafta6"))
        self.cmb_hafta.setItemText(6, _translate("Form", "Hafta7"))
        self.cmb_hafta.setItemText(7, _translate("Form", "Hafta8"))
        self.cmb_hafta.setItemText(8, _translate("Form", "Hafta9"))
        self.cmb_hafta.setItemText(9, _translate("Form", "Hafta10"))
        self.cmb_hafta.setItemText(10, _translate("Form", "Hafta11"))
        self.cmb_hafta.setItemText(11, _translate("Form", "Hafta12"))
        self.cmb_hafta.setItemText(12, _translate("Form", "Hafta13"))
        self.cmb_hafta.setItemText(13, _translate("Form", "Hafta14"))
        self.label_4.setText(_translate("Form", "Kaçıncı hafta"))
        self.yklm_btn.setText(_translate("Form", "Yoklamayı Başlat"))
        self.yoklama_bt.setText(_translate("Form", "Yoklama Takibi"))
        self.qrcode_bt.setText(_translate("Form", "Qr Kod Oluştur"))
        self.cikis_bt.setText(_translate("Form", "Çıkış"))
        self.groupBox.setTitle(_translate("Form", "QR Kod Oluştur"))
        self.label.setText(_translate("Form", "Öğrenci Numarası:"))
        self.label_2.setText(_translate("Form", "Öğrenci Adı:"))
        self.label_3.setText(_translate("Form", "Öğrenci Soyadı:"))
        self.control_bt.setText(_translate("Form", "Yoklama Başlat"))
